[linuxservers]
127.0.0.1:2525 

#ansible_user: root
#vmint ansible_host=127.0.0.1 ansible_port=2525 ansible_user=root ansible_ssh_pass="password123" role="primary"
#icpeeproxymgmt01.imidevops.com ansible_host=169.50.223.238 ansible_user=root ansible_ssh_pass="W8QAwWrl" role="primary"
#169.50.223.238
#icpeeproxymgmt01.imidevops.com ansible_host=169.50.223.238 ansible_user=root ansible_ssh_pass="W8QAwWrl" role="primary"
#vmint ansible_host=127.0.0.1 ansible_port=2525 ansible_user=root ansible_ssh_pass="password123"



